
site_name: SMX Blockchain Course
repo_url: https://github.com/dmtrbch/smx-blockchain-course
edit_uri: edit/staging/docs/
theme:
  name: null
  custom_dir: 'custom_theme/'
markdown_extensions:
  - attr_list
  - codehilite